apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    name: letsencrypt-prod
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Values.letsencrypt.secretName }}
    server: {{ .Values.letsencrypt.url }}
    solvers:
      - http01:
          ingress:
            class: nginx
