apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.app }}
  labels:
    app: {{ .Values.frontend.app }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.app }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: {{ .Values.frontend.deployment.image }}
          ports:
            - containerPort: {{ .Values.frontend.deployment.containerPort }}
