openapi: 3.0.3
info:
  title: Web Gaming Sandbox
  version: 0.0.1
paths:
  /ping:
    get:
      responses:
        200:
          description: Basic ping response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
